using System.Collections.Generic;
using System.Drawing;
using System.Globalization;

namespace DragNWash.Installer
{
    // The installer's own words, in English, Japanese and Chinese. The mod's words
    // (its name, choice labels) come from mod-install.json. Log lines stay English
    // so they read the same in a bug report.
    internal static class Strings
    {
        internal enum Key
        {
            Title,
            GameFolder,
            Browse,
            NotFound,
            Running,
            NoPayload,
            BadManifest,
            BepInExHash,
            OtherLoader,
            OtherLoaderNamed,
            RolledBack,
            RolledBackPartly,
            Install,
            Update,
            Uninstall,
            KeepData,
            AlsoBepInEx,
            Installed,
            Uninstalled,
            StatusBepInEx,
            StatusMod,
            Yes,
            No,
            Language,
            Website,
            Working,
            SteamLaunchHint,
            Action,
            NothingToUninstall,
            InstallButton,
            UpdateButton,
            UninstallButton,
            Close,
            InstallWill,
            UninstallWill,
            SmartScreenHint,
            ListAnd,
            ListComma,
            PlanDownloadBepInEx,
            PlanHaveBepInEx,
            PlanFrameworkAndMod,
            PlanMod,
            PlanKeepNewerFramework,
            PlanBackup,
            PlanSet,
            PlanNothingElse,
            PlanOtherLoader,
            PlanOtherLoaderNamed,
            PlanRemovePlugin,
            PlanRemovePluginKeep,
            PlanRemoveConfig,
            PlanRemoveInstallerFolder,
            PlanRemoveFramework,
            PlanKeepFramework,
            PlanRemoveSaveHistory,
            PlanRemoveBepInEx,
            PlanRemoveBepInExKeep,
            PlanKeepBepInEx,
            PlanKeepBepInExUsed,
            Cancel,
            Downloading,
            Cancelled,
            Stopped,
            DownloadFailed,
            DownloadFailedHelp,
            CannotWrite,
            CannotWriteHelp,
            BadZip,
            BadZipHelp,
            SomethingWrong,
            SomethingWrongHelp,
            ShowDetails,
            HideDetails,
            CopyDetails,
            Retry,
            StatusFramework,
            PlanDownloadFramework,
            PlanFrameworkBring,
            PlanFrameworkBringOne,
            PlanFrameworkBringCore,
            PlanFrameworkSatisfied,
            SmartScreenHintFramework,
            InstallingNow,
            DoneList,
            Done,
            DownloadHint,
            StepChecked,
            StepDownload,
            StepDownloading,
            StepHash,
            StepHashBoth,
            StepBackup,
            StepPutBepInEx,
            StepPutBoth,
            StepPut,
            StepSet,
            DoneFramework,
            DoneChecked,
            DoneKeptSame,
            DoneKeptNewer,
            DoneFrameworkSatisfied,
            DoneKeptFramework,
            DoneNotInstalled,
            DoneBepInEx,
            DoneSetting,
            DoneOtherMods,
            DoneOtherModsOne,
            DoneBackup,
            DoneBackupOne,
            PartPreloader,
            ConsentHead,
            ConsentNeedOlder,
            ConsentNeedMissing,
            ConsentNeedParts,
            ConsentWhere,
            ConsentWhereText,
            ConsentWhy,
            ConsentWhyText,
            ConsentSent,
            ConsentSentText,
            ConsentCheck,
            ConsentCheckText,
            ConsentCheckTextBoth,
            ConsentNoApi,
            ConsentNoApiBepInEx,
            OpenReleasePage,
            ChooseZip,
            DownloadAndInstall,
            CancelPlain,
            ChooseZipTitle,
            NetOffline,
            NetBusy,
            NetLimited,
            NetLimitedLater,
            NetTls,
            FwNotPublished,
            FwDownloadFailed,
            FwSize,
            FwHash,
            FwLocalMismatch,
            FwNoDownload,
            BepInExNoDownload,
            FwZipLacks,
            FwZipTooOld,
            FwKeepNotMet,
            NothingChanged,
            FwDeletedHelp,
            FwNotUsedHelp,
            FwManualHelp,
            FwReleaseLink,
            FwKeepLink,
        }

        private static readonly Dictionary<string, Dictionary<Key, string>> All = new Dictionary<string, Dictionary<Key, string>>
        {
            ["en"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} installer",
                [Key.GameFolder] = "Game folder",
                [Key.Browse] = "Browse...",
                [Key.NotFound] = "Drag'n Wash was not found. Choose the game folder (the one with DragNWash.exe).",
                [Key.Running] = "Close the game first.",
                [Key.NoPayload] = "The mod's files are missing next to the installer. Extract the whole zip first, then run Install.exe from the extracted folder.",
                [Key.BadManifest] = "mod-install.json next to the installer could not be read.",
                [Key.BepInExHash] = "The BepInEx download is corrupt or has been tampered with (SHA-256 mismatch). Nothing was installed.",
                [Key.OtherLoader] = "Another mod loader is in this game folder. Only one loader can be installed per game folder, so nothing was changed.",
                [Key.OtherLoaderNamed] = "Another mod loader ({0}) is in this game folder. Only one loader can be installed per game folder, so nothing was changed.",
                [Key.RolledBack] = "Something went wrong while copying, so everything was put back as it was ({0} files).",
                [Key.RolledBackPartly] = "Something went wrong while copying, and {0} files could not be put back. The files it replaced are kept in {1}.",
                [Key.Install] = "Install",
                [Key.Update] = "Update",
                [Key.Uninstall] = "Uninstall",
                [Key.KeepData] = "Keep save history and the mod's working files",
                [Key.AlsoBepInEx] = "Also remove BepInEx when no other mod is left",
                [Key.Installed] = "Done. Start the game from Steam.",
                [Key.Uninstalled] = "Uninstalled.",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "Installed version",
                [Key.Yes] = "installed",
                [Key.No] = "not installed",
                [Key.Language] = "Installer language",
                [Key.Website] = "Website",
                [Key.Working] = "Working...",
                [Key.SteamLaunchHint] = "Mods can also be uninstalled in the game: Options → Mods.",
                [Key.Action] = "Action",
                [Key.NothingToUninstall] = "(nothing to uninstall)",
                [Key.InstallButton] = "&Install",
                [Key.UpdateButton] = "&Update",
                [Key.UninstallButton] = "&Uninstall",
                [Key.Close] = "&Close",
                [Key.InstallWill] = "Install will:",
                [Key.UninstallWill] = "Uninstall will:",
                [Key.SmartScreenHint] = "Windows SmartScreen or Defender may warn about Install.exe: it is not code-signed. The list above is all it does.",
                [Key.ListAnd] = " and ",
                [Key.ListComma] = ", ",
                [Key.PlanDownloadBepInEx] = "Download BepInEx {0} from {1} (served by {2}) and check its SHA-256",
                [Key.PlanHaveBepInEx] = "Use the BepInEx that is already in the game folder",
                [Key.PlanFrameworkAndMod] = "Put Drag'n Wash ModFramework {0} and {1} into BepInEx\\plugins (files you added there are kept)",
                [Key.PlanMod] = "Put {0} into BepInEx\\plugins (files you added there are kept)",
                [Key.PlanKeepNewerFramework] = "Keep Drag'n Wash ModFramework {0}, which is newer than the one in this zip",
                [Key.PlanBackup] = "Copy every file it replaces to BepInEx\\DragNWash.Installer\\backup first",
                [Key.PlanSet] = "Set {0} = {1} in BepInEx\\config\\{2}",
                [Key.PlanNothingElse] = "Nothing else is downloaded or changed.",
                [Key.PlanOtherLoader] = "Stop without changing anything: another mod loader is in this game folder, and a game folder can have only one loader",
                [Key.PlanOtherLoaderNamed] = "Stop without changing anything: another mod loader ({0}) is in this game folder, and a game folder can have only one loader",
                [Key.PlanRemovePlugin] = "Remove BepInEx\\plugins\\{0}",
                [Key.PlanRemovePluginKeep] = "Remove BepInEx\\plugins\\{0}, keeping {1}",
                [Key.PlanRemoveConfig] = "Remove BepInEx\\config\\{0}",
                [Key.PlanRemoveInstallerFolder] = "Remove the installer's backup in BepInEx\\DragNWash.Installer",
                [Key.PlanRemoveFramework] = "Remove Drag'n Wash ModFramework too (no other mod uses it)",
                [Key.PlanKeepFramework] = "Keep Drag'n Wash ModFramework (other mods use it: {0})",
                [Key.PlanRemoveSaveHistory] = "Remove the save history in BepInEx\\SaveHistory",
                [Key.PlanRemoveBepInEx] = "Remove BepInEx",
                [Key.PlanRemoveBepInExKeep] = "Remove BepInEx; your kept data stays in the BepInEx folder",
                [Key.PlanKeepBepInEx] = "Keep BepInEx",
                [Key.PlanKeepBepInExUsed] = "Keep BepInEx (other mods or patchers use it)",
                [Key.Cancel] = "&Cancel",
                [Key.Downloading] = "Downloading {0} from {1}",
                [Key.Cancelled] = "Cancelled. Nothing was changed in the game folder.",
                [Key.Stopped] = "Stopped.",
                [Key.DownloadFailed] = "BepInEx could not be downloaded.",
                [Key.DownloadFailedHelp] = "Check the internet connection and try again. Nothing was changed in the game folder.",
                [Key.CannotWrite] = "Could not write to the game folder.",
                [Key.CannotWriteHelp] = "A file there may be in use or read-only. Close the game and anything else using its folder, then try again.",
                [Key.BadZip] = "The download is not a valid zip.",
                [Key.BadZipHelp] = "Try again. If it keeps happening, copy the details into a bug report.",
                [Key.SomethingWrong] = "Something went wrong.",
                [Key.SomethingWrongHelp] = "Copy the details into a bug report on the mod's website.",
                [Key.ShowDetails] = "Show details",
                [Key.HideDetails] = "Hide details",
                [Key.CopyDetails] = "Copy &details",
                [Key.Retry] = "&Retry",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "Download Drag'n Wash ModFramework {0} from {1} (served by {2}) and check its SHA-256",
                [Key.PlanFrameworkBring] = "Bring the framework core and the {0} libraries this mod uses up to {1} (a newer one already there is kept)",
                [Key.PlanFrameworkBringOne] = "Bring the framework core and the library this mod uses up to {1} (a newer one already there is kept)",
                [Key.PlanFrameworkBringCore] = "Bring the framework core up to {1} (a newer one already there is kept)",
                [Key.PlanFrameworkSatisfied] = "Keep Drag'n Wash ModFramework {0}: it has everything this mod needs, so nothing is downloaded",
                [Key.SmartScreenHintFramework] = "Windows SmartScreen or Defender may warn about Install.exe: it is not code-signed, and it downloads ModFramework from the internet. The list above is all it does.",
                [Key.InstallingNow] = "Installing:",
                [Key.DoneList] = "Done:",
                [Key.Done] = "Done.",
                [Key.DownloadHint] = "Nothing in the game folder changes until the download is checked, so Cancel leaves it as it was.",
                [Key.StepChecked] = "Checked what is installed: ModFramework {0}, BepInEx {1}, no other mod loader",
                [Key.StepDownload] = "Download {0} from {1}",
                [Key.StepDownloading] = "Downloading {0} of {1}: {2} ({3} KB of {4} KB)",
                [Key.StepHash] = "Check its SHA-256",
                [Key.StepHashBoth] = "Check their SHA-256",
                [Key.StepBackup] = "Copy the files it replaces to BepInEx\\DragNWash.Installer\\backup",
                [Key.StepPutBepInEx] = "Put BepInEx {0} into the game folder",
                [Key.StepPutBoth] = "Put ModFramework and {0} into BepInEx\\plugins",
                [Key.StepPut] = "Put {0} into BepInEx\\plugins",
                [Key.StepSet] = "Set {0} = {1}",
                [Key.DoneFramework] = "ModFramework {0}: {1}",
                [Key.DoneChecked] = " (SHA-256 checked)",
                [Key.DoneKeptSame] = "Kept {0}: already the same version",
                [Key.DoneKeptNewer] = "Kept {0}: newer than the one in ModFramework {1}",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0}: it already has everything this mod needs, nothing was downloaded",
                [Key.DoneKeptFramework] = "Kept ModFramework {0}: it meets this mod's minimums",
                [Key.DoneNotInstalled] = "Not installed: {0} (this mod does not use them)",
                [Key.DoneBepInEx] = "BepInEx {0} (SHA-256 checked)",
                [Key.DoneSetting] = "{0} = {1}",
                [Key.DoneOtherMods] = "Other mods: {0} folders in BepInEx\\plugins, not touched",
                [Key.DoneOtherModsOne] = "Other mods: 1 folder in BepInEx\\plugins, not touched",
                [Key.DoneBackup] = "The {0} replaced files are kept in {1}",
                [Key.DoneBackupOne] = "The replaced file is kept in {1}",
                [Key.PartPreloader] = "the Preloader",
                [Key.ConsentHead] = "The installer will connect to the internet",
                [Key.ConsentNeedOlder] = "This mod needs Drag'n Wash ModFramework {0}, and the game folder has {1}. The installer will get it from the framework's GitHub release.",
                [Key.ConsentNeedMissing] = "This mod needs Drag'n Wash ModFramework {0}, and the game folder does not have it. The installer will get it from the framework's GitHub release.",
                [Key.ConsentNeedParts] = "This mod needs parts of Drag'n Wash ModFramework {0} that the game folder does not have. The installer will get them from the framework's GitHub release.",
                [Key.ConsentWhere] = "Where",
                [Key.ConsentWhereText] = "github.com (the releases of {0})\r\n{1} (where GitHub keeps the file; github.com sends the installer there)",
                [Key.ConsentWhy] = "Why",
                [Key.ConsentWhyText] = "To get {0}, once.",
                [Key.ConsentSent] = "Sent",
                [Key.ConsentSentText] = "An ordinary HTTPS request with the User-Agent {0}. Not your name, not your folders, no sign-in, no cookies. Like any website, GitHub sees your IP address.",
                [Key.ConsentCheck] = "Check",
                [Key.ConsentCheckText] = "Used only if its SHA-256 matches the one recorded in this mod's release. Until then nothing in the game folder changes.",
                [Key.ConsentCheckTextBoth] = "Each is used only if its SHA-256 matches the one recorded in this mod's release (ModFramework) or in the installer (BepInEx). Until then nothing in the game folder changes.",
                [Key.ConsentNoApi] = "api.github.com is not contacted. Choosing a zip you downloaded yourself uses no internet at all.",
                [Key.ConsentNoApiBepInEx] = "api.github.com is not contacted. Choosing a ModFramework zip you downloaded yourself still downloads BepInEx.",
                [Key.OpenReleasePage] = "Open the release page",
                [Key.ChooseZip] = "Choose &zip...",
                [Key.DownloadAndInstall] = "&Download and install",
                [Key.CancelPlain] = "Cancel",
                [Key.ChooseZipTitle] = "Choose {0}",
                [Key.NetOffline] = "The installer cannot reach the internet.",
                [Key.NetBusy] = "GitHub did not answer, or answered with an error. Try again in a few minutes.",
                [Key.NetLimited] = "GitHub is limiting downloads right now. Try again in {0} minutes.",
                [Key.NetLimitedLater] = "GitHub is limiting downloads right now. Try again later.",
                [Key.NetTls] = "A secure connection to GitHub could not be confirmed.",
                [Key.FwNotPublished] = "ModFramework {0} is not published yet. Please tell the mod's author.",
                [Key.FwDownloadFailed] = "ModFramework {0} could not be downloaded.",
                [Key.FwSize] = "The downloaded ModFramework {0} is not the size recorded in this mod's release.",
                [Key.FwHash] = "The downloaded ModFramework {0} does not match the one recorded in this mod's release (SHA-256).",
                [Key.FwLocalMismatch] = "The chosen zip is not the ModFramework {0} recorded in this mod's release (size or SHA-256).",
                [Key.FwNoDownload] = "ModFramework {0} has to be downloaded, but downloading is turned off (--no-download). Pass the zip with --framework-zip.",
                [Key.BepInExNoDownload] = "BepInEx {0} has to be downloaded, but downloading is turned off (--no-download). Pass the zip with --bepinex-zip.",
                [Key.FwZipLacks] = "ModFramework {0} does not have {1}, which this mod needs. Please tell the mod's author.",
                [Key.FwZipTooOld] = "ModFramework {0} has {1} {2}, but this mod needs {3} or newer. Please tell the mod's author.",
                [Key.FwKeepNotMet] = "The installed ModFramework does not meet this mod's minimums, so ModFramework {0} has to be installed.",
                [Key.NothingChanged] = "Nothing was changed in the game folder.",
                [Key.FwDeletedHelp] = "The file was not used and has been deleted. Nothing was changed in the game folder.",
                [Key.FwNotUsedHelp] = "The zip was not used. Nothing was changed in the game folder.",
                [Key.FwManualHelp] = "You can download the zip yourself from the release page and pick it with “Choose zip”. It is checked the same way.",
                [Key.FwReleaseLink] = "Open the release page ({0})",
                [Key.FwKeepLink] = "Install only the mod and keep ModFramework {0} (it meets this mod's minimums)",
            },
            ["ja"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} インストーラー",
                [Key.GameFolder] = "ゲームのフォルダー",
                [Key.Browse] = "参照...",
                [Key.NotFound] = "Drag'n Wash が見つかりません。ゲームのフォルダー（DragNWash.exe がある場所）を選んでください。",
                [Key.Running] = "先にゲームを終了してください。",
                [Key.NoPayload] = "インストーラーの隣に Mod のファイルがありません。zip を丸ごと展開してから、展開したフォルダーの Install.exe を実行してください。",
                [Key.BadManifest] = "インストーラーの隣にある mod-install.json を読めませんでした。",
                [Key.BepInExHash] = "ダウンロードした BepInEx が壊れているか、改ざんされています（SHA-256 が一致しません）。何もインストールしていません。",
                [Key.OtherLoader] = "別の Mod ローダーが入っています。1 つのゲームフォルダーに入れられるローダーは 1 つだけなので、何も変更していません。",
                [Key.OtherLoaderNamed] = "別の Mod ローダー（{0}）が入っています。1 つのゲームフォルダーに入れられるローダーは 1 つだけなので、何も変更していません。",
                [Key.RolledBack] = "コピーの途中で失敗したため、すべて元に戻しました（{0} ファイル）。",
                [Key.RolledBackPartly] = "コピーの途中で失敗し、{0} ファイルを元に戻せませんでした。上書きしたファイルの控えは {1} にあります。",
                [Key.Install] = "インストール",
                [Key.Update] = "更新",
                [Key.Uninstall] = "アンインストール",
                [Key.KeepData] = "セーブ履歴と Mod の作業ファイルは残す",
                [Key.AlsoBepInEx] = "ほかの Mod が残っていなければ BepInEx も削除する",
                [Key.Installed] = "完了しました。Steam からゲームを起動してください。",
                [Key.Uninstalled] = "アンインストールしました。",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "入っているバージョン",
                [Key.Yes] = "導入済み",
                [Key.No] = "未導入",
                [Key.Language] = "インストーラーの言語",
                [Key.Website] = "Web サイト",
                [Key.Working] = "処理中...",
                [Key.SteamLaunchHint] = "Mod はゲームの中（Options → Mods）からもアンインストールできます。",
                [Key.Action] = "操作",
                [Key.NothingToUninstall] = "（アンインストールするものはありません）",
                [Key.InstallButton] = "インストール(&I)",
                [Key.UpdateButton] = "更新(&U)",
                [Key.UninstallButton] = "アンインストール(&U)",
                [Key.Close] = "閉じる(&C)",
                [Key.InstallWill] = "インストールで行うこと：",
                [Key.UninstallWill] = "アンインストールで行うこと：",
                [Key.SmartScreenHint] = "Install.exe はコード署名がないため、Windows SmartScreen や Defender が警告することがあります。行うのは上の一覧にあることだけです。",
                [Key.ListAnd] = " と ",
                [Key.ListComma] = "、",
                [Key.PlanDownloadBepInEx] = "BepInEx {0} を {1}（転送先 {2}）からダウンロードし、SHA-256 を確認する",
                [Key.PlanHaveBepInEx] = "ゲームのフォルダーにすでにある BepInEx を使う",
                [Key.PlanFrameworkAndMod] = "Drag'n Wash ModFramework {0} と {1} を BepInEx\\plugins に配置する（自分で追加したファイルはそのまま残す）",
                [Key.PlanMod] = "{0} を BepInEx\\plugins に配置する（自分で追加したファイルはそのまま残す）",
                [Key.PlanKeepNewerFramework] = "Drag'n Wash ModFramework {0} はこの zip のものより新しいので、そのまま残す",
                [Key.PlanBackup] = "上書きするファイルは、先に BepInEx\\DragNWash.Installer\\backup に控える",
                [Key.PlanSet] = "「{0}」を「{1}」に設定する（BepInEx\\config\\{2}）",
                [Key.PlanNothingElse] = "これ以外のダウンロードや変更は行いません。",
                [Key.PlanOtherLoader] = "別の Mod ローダーが入っているので、何も変更せずに止める（1 つのゲームフォルダーに入れられるローダーは 1 つだけ）",
                [Key.PlanOtherLoaderNamed] = "別の Mod ローダー（{0}）が入っているので、何も変更せずに止める（1 つのゲームフォルダーに入れられるローダーは 1 つだけ）",
                [Key.PlanRemovePlugin] = "BepInEx\\plugins\\{0} を削除する",
                [Key.PlanRemovePluginKeep] = "BepInEx\\plugins\\{0} を削除する（{1} は残す）",
                [Key.PlanRemoveConfig] = "BepInEx\\config\\{0} を削除する",
                [Key.PlanRemoveInstallerFolder] = "BepInEx\\DragNWash.Installer にあるインストーラーの控えを削除する",
                [Key.PlanRemoveFramework] = "Drag'n Wash ModFramework も削除する（ほかに使っている Mod がない）",
                [Key.PlanKeepFramework] = "Drag'n Wash ModFramework は残す（ほかの Mod が使っている：{0}）",
                [Key.PlanRemoveSaveHistory] = "BepInEx\\SaveHistory のセーブ履歴を削除する",
                [Key.PlanRemoveBepInEx] = "BepInEx を削除する",
                [Key.PlanRemoveBepInExKeep] = "BepInEx を削除する（残すデータは BepInEx フォルダーに置いたまま）",
                [Key.PlanKeepBepInEx] = "BepInEx は残す",
                [Key.PlanKeepBepInExUsed] = "BepInEx は残す（ほかの Mod かパッチャーが使っている）",
                [Key.Cancel] = "キャンセル(&C)",
                [Key.Downloading] = "{0} を {1} からダウンロード中",
                [Key.Cancelled] = "中止しました。ゲームのフォルダーは何も変わっていません。",
                [Key.Stopped] = "中断しました。",
                [Key.DownloadFailed] = "BepInEx をダウンロードできませんでした。",
                [Key.DownloadFailedHelp] = "インターネット接続を確認して、もう一度試してください。ゲームのフォルダーは何も変わっていません。",
                [Key.CannotWrite] = "ゲームのフォルダーに書き込めませんでした。",
                [Key.CannotWriteHelp] = "ファイルが使用中か、読み取り専用になっている可能性があります。ゲームと、そのフォルダーを使っているほかのプログラムを閉じてから、もう一度試してください。",
                [Key.BadZip] = "ダウンロードしたファイルが正しい zip ではありません。",
                [Key.BadZipHelp] = "もう一度試してください。何度も失敗する場合は、詳細をコピーしてバグ報告に貼ってください。",
                [Key.SomethingWrong] = "問題が発生しました。",
                [Key.SomethingWrongHelp] = "詳細をコピーして、Mod の Web サイトでバグ報告に貼ってください。",
                [Key.ShowDetails] = "詳細を表示",
                [Key.HideDetails] = "詳細を隠す",
                [Key.CopyDetails] = "詳細をコピー(&D)",
                [Key.Retry] = "再試行(&R)",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "Drag'n Wash ModFramework {0} を {1}（転送先 {2}）からダウンロードし、SHA-256 を確認する",
                [Key.PlanFrameworkBring] = "ModFramework の core と、この Mod が使う {0} つのライブラリを {1} にする（入っている方が新しければそのまま残す）",
                [Key.PlanFrameworkBringOne] = "ModFramework の core と、この Mod が使うライブラリを {1} にする（入っている方が新しければそのまま残す）",
                [Key.PlanFrameworkBringCore] = "ModFramework の core を {1} にする（入っている方が新しければそのまま残す）",
                [Key.PlanFrameworkSatisfied] = "Drag'n Wash ModFramework {0} にはこの Mod に要るものがそろっているので、そのまま使う（ダウンロードしない）",
                [Key.SmartScreenHintFramework] = "Install.exe はコード署名がなく、ModFramework をインターネットから取得するため、Windows SmartScreen や Defender が警告することがあります。行うのは上の一覧にあることだけです。",
                [Key.InstallingNow] = "インストール中：",
                [Key.DoneList] = "行ったこと：",
                [Key.Done] = "完了しました。",
                [Key.DownloadHint] = "ダウンロードを確認し終わるまでゲームのフォルダーは変えないので、キャンセルしても元のままです。",
                [Key.StepChecked] = "入っているものを確認した：ModFramework {0}、BepInEx {1}、ほかのローダーなし",
                [Key.StepDownload] = "{0} を {1} からダウンロードする",
                [Key.StepDownloading] = "ダウンロード中 {0} / {1}：{2}（{3} KB / {4} KB）",
                [Key.StepHash] = "SHA-256 を確認する",
                [Key.StepHashBoth] = "SHA-256 を確認する",
                [Key.StepBackup] = "上書きするファイルを BepInEx\\DragNWash.Installer\\backup に控える",
                [Key.StepPutBepInEx] = "BepInEx {0} をゲームのフォルダーに配置する",
                [Key.StepPutBoth] = "ModFramework と {0} を BepInEx\\plugins に配置する",
                [Key.StepPut] = "{0} を BepInEx\\plugins に配置する",
                [Key.StepSet] = "「{0}」を「{1}」に設定する",
                [Key.DoneFramework] = "ModFramework {0}：{1}",
                [Key.DoneChecked] = "（SHA-256 確認済み）",
                [Key.DoneKeptSame] = "{0} は同じ版なので、そのまま",
                [Key.DoneKeptNewer] = "{0} は ModFramework {1} のものより新しいので、そのまま",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0} にはこの Mod に要るものがそろっていたので、ダウンロードしていません",
                [Key.DoneKeptFramework] = "ModFramework {0} はこの Mod の最低条件を満たすので、そのまま",
                [Key.DoneNotInstalled] = "入れなかったもの：{0}（この Mod は使いません）",
                [Key.DoneBepInEx] = "BepInEx {0}（SHA-256 確認済み）",
                [Key.DoneSetting] = "「{0}」＝「{1}」",
                [Key.DoneOtherMods] = "ほかの Mod：BepInEx\\plugins の {0} フォルダーには触れていません",
                [Key.DoneOtherModsOne] = "ほかの Mod：BepInEx\\plugins の 1 フォルダーには触れていません",
                [Key.DoneBackup] = "上書きした {0} ファイルの控え：{1}",
                [Key.DoneBackupOne] = "上書きした 1 ファイルの控え：{1}",
                [Key.PartPreloader] = "Preloader",
                [Key.ConsentHead] = "インターネットに接続します",
                [Key.ConsentNeedOlder] = "この Mod には Drag'n Wash ModFramework {0} が必要です。ゲームのフォルダーにあるのは {1} です。フレームワークの GitHub のリリースから取得します。",
                [Key.ConsentNeedMissing] = "この Mod には Drag'n Wash ModFramework {0} が必要です。ゲームのフォルダーにはありません。フレームワークの GitHub のリリースから取得します。",
                [Key.ConsentNeedParts] = "この Mod には Drag'n Wash ModFramework {0} の一部が必要ですが、ゲームのフォルダーにありません。フレームワークの GitHub のリリースから取得します。",
                [Key.ConsentWhere] = "接続先",
                [Key.ConsentWhereText] = "github.com（{0} のリリース）\r\n{1}（GitHub がファイルを置いている場所。github.com から自動で転送されます）",
                [Key.ConsentWhy] = "目的",
                [Key.ConsentWhyText] = "{0} を 1 回だけ取得します。",
                [Key.ConsentSent] = "送るもの",
                [Key.ConsentSentText] = "通常の HTTPS のリクエストと User-Agent {0} だけです。名前、フォルダーの場所、ログイン情報、Cookie は送りません。どの Web サイトとも同じく、GitHub には IP アドレスが見えます。",
                [Key.ConsentCheck] = "確認",
                [Key.ConsentCheckText] = "SHA-256 がこの Mod のリリースに記録された値と一致したときだけ使います。それまでゲームのフォルダーは変わりません。",
                [Key.ConsentCheckTextBoth] = "どちらも、SHA-256 がこの Mod のリリース（ModFramework）かインストーラー（BepInEx）に記録された値と一致したときだけ使います。それまでゲームのフォルダーは変わりません。",
                [Key.ConsentNoApi] = "api.github.com には接続しません。自分でダウンロードした zip を選べば、インターネットは使いません。",
                [Key.ConsentNoApiBepInEx] = "api.github.com には接続しません。自分でダウンロードした ModFramework の zip を選んでも、BepInEx はダウンロードします。",
                [Key.OpenReleasePage] = "リリースのページを開く",
                [Key.ChooseZip] = "zip を選ぶ(&Z)...",
                [Key.DownloadAndInstall] = "ダウンロードしてインストール(&D)",
                [Key.CancelPlain] = "キャンセル",
                [Key.ChooseZipTitle] = "{0} を選ぶ",
                [Key.NetOffline] = "インターネットにつながりません。",
                [Key.NetBusy] = "GitHub が応答しないか、エラーを返しました。数分後にもう一度試してください。",
                [Key.NetLimited] = "GitHub の利用制限に達しました。{0} 分後にもう一度試してください。",
                [Key.NetLimitedLater] = "GitHub の利用制限に達しました。しばらくしてからもう一度試してください。",
                [Key.NetTls] = "安全な接続を確認できませんでした。",
                [Key.FwNotPublished] = "ModFramework {0} がまだ公開されていません。Mod の作者に知らせてください。",
                [Key.FwDownloadFailed] = "ModFramework {0} をダウンロードできませんでした。",
                [Key.FwSize] = "ダウンロードした ModFramework {0} のサイズが、この Mod のリリースに記録されたものと違います。",
                [Key.FwHash] = "ダウンロードした ModFramework {0} が、この Mod のリリースに記録されたものと一致しません（SHA-256）。",
                [Key.FwLocalMismatch] = "選んだ zip は、この Mod のリリースに記録された ModFramework {0} ではありません（サイズか SHA-256 が違います）。",
                [Key.FwNoDownload] = "ModFramework {0} のダウンロードが必要ですが、ダウンロードはオフです（--no-download）。--framework-zip で zip を渡してください。",
                [Key.BepInExNoDownload] = "BepInEx {0} のダウンロードが必要ですが、ダウンロードはオフです（--no-download）。--bepinex-zip で zip を渡してください。",
                [Key.FwZipLacks] = "ModFramework {0} に、この Mod が必要とする {1} が入っていません。Mod の作者に知らせてください。",
                [Key.FwZipTooOld] = "ModFramework {0} の {1} は {2} ですが、この Mod には {3} 以上が必要です。Mod の作者に知らせてください。",
                [Key.FwKeepNotMet] = "入っている ModFramework はこの Mod の最低条件を満たさないので、ModFramework {0} を入れる必要があります。",
                [Key.NothingChanged] = "ゲームのフォルダーは何も変わっていません。",
                [Key.FwDeletedHelp] = "ファイルは使わずに削除しました。ゲームのフォルダーは何も変わっていません。",
                [Key.FwNotUsedHelp] = "zip は使っていません。ゲームのフォルダーは何も変わっていません。",
                [Key.FwManualHelp] = "リリースのページから zip を自分でダウンロードし、「zip を選ぶ」で選ぶこともできます。同じように確かめます。",
                [Key.FwReleaseLink] = "リリースのページを開く（{0}）",
                [Key.FwKeepLink] = "ModFramework {0} のまま、Mod だけ入れる（この Mod の最低条件は満たしています）",
            },
            ["zh"] = new Dictionary<Key, string>
            {
                [Key.Title] = "{0} 安装器",
                [Key.GameFolder] = "游戏文件夹",
                [Key.Browse] = "浏览...",
                [Key.NotFound] = "未找到 Drag'n Wash。请选择游戏文件夹（包含 DragNWash.exe 的文件夹）。",
                [Key.Running] = "请先关闭游戏。",
                [Key.NoPayload] = "安装器旁边缺少模组文件。请先完整解压 zip，再运行解压后文件夹中的 Install.exe。",
                [Key.BadManifest] = "无法读取安装器旁边的 mod-install.json。",
                [Key.BepInExHash] = "下载的 BepInEx 已损坏或被篡改（SHA-256 不一致）。未安装任何内容。",
                [Key.OtherLoader] = "此游戏文件夹中已有另一个模组加载器。一个游戏文件夹只能安装一个加载器，因此没有做任何更改。",
                [Key.OtherLoaderNamed] = "此游戏文件夹中已有另一个模组加载器（{0}）。一个游戏文件夹只能安装一个加载器，因此没有做任何更改。",
                [Key.RolledBack] = "复制过程中出错，已将所有内容恢复原样（{0} 个文件）。",
                [Key.RolledBackPartly] = "复制过程中出错，有 {0} 个文件无法恢复。被覆盖文件的备份保存在 {1}。",
                [Key.Install] = "安装",
                [Key.Update] = "更新",
                [Key.Uninstall] = "卸载",
                [Key.KeepData] = "保留存档历史和模组的工作文件",
                [Key.AlsoBepInEx] = "没有其他模组时同时删除 BepInEx",
                [Key.Installed] = "完成。请从 Steam 启动游戏。",
                [Key.Uninstalled] = "已卸载。",
                [Key.StatusBepInEx] = "BepInEx",
                [Key.StatusMod] = "已安装的版本",
                [Key.Yes] = "已安装",
                [Key.No] = "未安装",
                [Key.Language] = "安装器语言",
                [Key.Website] = "网站",
                [Key.Working] = "处理中...",
                [Key.SteamLaunchHint] = "也可以在游戏中（Options → Mods）卸载模组。",
                [Key.Action] = "操作",
                [Key.NothingToUninstall] = "（没有可卸载的内容）",
                [Key.InstallButton] = "安装(&I)",
                [Key.UpdateButton] = "更新(&U)",
                [Key.UninstallButton] = "卸载(&U)",
                [Key.Close] = "关闭(&C)",
                [Key.InstallWill] = "安装将会：",
                [Key.UninstallWill] = "卸载将会：",
                [Key.SmartScreenHint] = "由于 Install.exe 没有代码签名，Windows SmartScreen 或 Defender 可能会发出警告。它只会执行上面列出的操作。",
                [Key.ListAnd] = " 和 ",
                [Key.ListComma] = "、",
                [Key.PlanDownloadBepInEx] = "从 {1}（转到 {2}）下载 BepInEx {0} 并校验 SHA-256",
                [Key.PlanHaveBepInEx] = "使用游戏文件夹中已有的 BepInEx",
                [Key.PlanFrameworkAndMod] = "将 Drag'n Wash ModFramework {0} 和 {1} 放入 BepInEx\\plugins（你自行添加的文件会保留）",
                [Key.PlanMod] = "将 {0} 放入 BepInEx\\plugins（你自行添加的文件会保留）",
                [Key.PlanKeepNewerFramework] = "保留 Drag'n Wash ModFramework {0}（其版本比此 zip 中的新）",
                [Key.PlanBackup] = "先将要覆盖的文件备份到 BepInEx\\DragNWash.Installer\\backup",
                [Key.PlanSet] = "将“{0}”设为“{1}”（BepInEx\\config\\{2}）",
                [Key.PlanNothingElse] = "不会下载或更改其他任何内容。",
                [Key.PlanOtherLoader] = "此游戏文件夹中已有另一个模组加载器，因此不做任何更改并停止（一个游戏文件夹只能安装一个加载器）",
                [Key.PlanOtherLoaderNamed] = "此游戏文件夹中已有另一个模组加载器（{0}），因此不做任何更改并停止（一个游戏文件夹只能安装一个加载器）",
                [Key.PlanRemovePlugin] = "删除 BepInEx\\plugins\\{0}",
                [Key.PlanRemovePluginKeep] = "删除 BepInEx\\plugins\\{0}，保留 {1}",
                [Key.PlanRemoveConfig] = "删除 BepInEx\\config\\{0}",
                [Key.PlanRemoveInstallerFolder] = "删除 BepInEx\\DragNWash.Installer 中安装器的备份",
                [Key.PlanRemoveFramework] = "同时删除 Drag'n Wash ModFramework（没有其他模组使用它）",
                [Key.PlanKeepFramework] = "保留 Drag'n Wash ModFramework（其他模组在使用：{0}）",
                [Key.PlanRemoveSaveHistory] = "删除 BepInEx\\SaveHistory 中的存档历史",
                [Key.PlanRemoveBepInEx] = "删除 BepInEx",
                [Key.PlanRemoveBepInExKeep] = "删除 BepInEx（保留的数据仍留在 BepInEx 文件夹中）",
                [Key.PlanKeepBepInEx] = "保留 BepInEx",
                [Key.PlanKeepBepInExUsed] = "保留 BepInEx（其他模组或补丁程序在使用）",
                [Key.Cancel] = "取消(&C)",
                [Key.Downloading] = "正在从 {1} 下载 {0}",
                [Key.Cancelled] = "已取消。游戏文件夹没有任何更改。",
                [Key.Stopped] = "已停止。",
                [Key.DownloadFailed] = "无法下载 BepInEx。",
                [Key.DownloadFailedHelp] = "请检查网络连接后重试。游戏文件夹没有任何更改。",
                [Key.CannotWrite] = "无法写入游戏文件夹。",
                [Key.CannotWriteHelp] = "文件夹中的文件可能正在被使用或为只读。请关闭游戏及其他正在使用该文件夹的程序，然后重试。",
                [Key.BadZip] = "下载的文件不是有效的 zip。",
                [Key.BadZipHelp] = "请重试。如果反复出现，请复制详情并提交错误报告。",
                [Key.SomethingWrong] = "出现了问题。",
                [Key.SomethingWrongHelp] = "请复制详情，在模组网站上提交错误报告。",
                [Key.ShowDetails] = "显示详情",
                [Key.HideDetails] = "隐藏详情",
                [Key.CopyDetails] = "复制详情(&D)",
                [Key.Retry] = "重试(&R)",
                [Key.StatusFramework] = "ModFramework",
                [Key.PlanDownloadFramework] = "从 {1}（转到 {2}）下载 Drag'n Wash ModFramework {0} 并校验 SHA-256",
                [Key.PlanFrameworkBring] = "将 ModFramework 的 core 和此模组使用的 {0} 个库更新到 {1}（已有的版本更新时保留）",
                [Key.PlanFrameworkBringOne] = "将 ModFramework 的 core 和此模组使用的库更新到 {1}（已有的版本更新时保留）",
                [Key.PlanFrameworkBringCore] = "将 ModFramework 的 core 更新到 {1}（已有的版本更新时保留）",
                [Key.PlanFrameworkSatisfied] = "保留 Drag'n Wash ModFramework {0}：此模组需要的都已具备，不会下载",
                [Key.SmartScreenHintFramework] = "由于 Install.exe 没有代码签名，并且会从互联网获取 ModFramework，Windows SmartScreen 或 Defender 可能会发出警告。它只会执行上面列出的操作。",
                [Key.InstallingNow] = "正在安装：",
                [Key.DoneList] = "已完成：",
                [Key.Done] = "完成。",
                [Key.DownloadHint] = "在下载校验完成前不会更改游戏文件夹，因此取消后一切保持原样。",
                [Key.StepChecked] = "已检查现有内容：ModFramework {0}，BepInEx {1}，没有其他加载器",
                [Key.StepDownload] = "从 {1} 下载 {0}",
                [Key.StepDownloading] = "正在下载 {0} / {1}：{2}（{3} KB / {4} KB）",
                [Key.StepHash] = "校验 SHA-256",
                [Key.StepHashBoth] = "校验 SHA-256",
                [Key.StepBackup] = "将要覆盖的文件备份到 BepInEx\\DragNWash.Installer\\backup",
                [Key.StepPutBepInEx] = "将 BepInEx {0} 放入游戏文件夹",
                [Key.StepPutBoth] = "将 ModFramework 和 {0} 放入 BepInEx\\plugins",
                [Key.StepPut] = "将 {0} 放入 BepInEx\\plugins",
                [Key.StepSet] = "将“{0}”设为“{1}”",
                [Key.DoneFramework] = "ModFramework {0}：{1}",
                [Key.DoneChecked] = "（已校验 SHA-256）",
                [Key.DoneKeptSame] = "保留 {0}：版本相同",
                [Key.DoneKeptNewer] = "保留 {0}：比 ModFramework {1} 中的更新",
                [Key.DoneFrameworkSatisfied] = "ModFramework {0}：此模组需要的都已具备，未下载",
                [Key.DoneKeptFramework] = "保留 ModFramework {0}：满足此模组的最低要求",
                [Key.DoneNotInstalled] = "未安装：{0}（此模组不使用）",
                [Key.DoneBepInEx] = "BepInEx {0}（已校验 SHA-256）",
                [Key.DoneSetting] = "“{0}”=“{1}”",
                [Key.DoneOtherMods] = "其他模组：未改动 BepInEx\\plugins 中的 {0} 个文件夹",
                [Key.DoneOtherModsOne] = "其他模组：未改动 BepInEx\\plugins 中的 1 个文件夹",
                [Key.DoneBackup] = "被覆盖的 {0} 个文件已备份到 {1}",
                [Key.DoneBackupOne] = "被覆盖的 1 个文件已备份到 {1}",
                [Key.PartPreloader] = "Preloader",
                [Key.ConsentHead] = "安装器将连接互联网",
                [Key.ConsentNeedOlder] = "此模组需要 Drag'n Wash ModFramework {0}，而游戏文件夹中是 {1}。安装器将从框架的 GitHub 发布页获取。",
                [Key.ConsentNeedMissing] = "此模组需要 Drag'n Wash ModFramework {0}，而游戏文件夹中没有。安装器将从框架的 GitHub 发布页获取。",
                [Key.ConsentNeedParts] = "此模组需要 Drag'n Wash ModFramework {0} 中游戏文件夹缺少的部分。安装器将从框架的 GitHub 发布页获取。",
                [Key.ConsentWhere] = "连接到",
                [Key.ConsentWhereText] = "github.com（{0} 的发布页）\r\n{1}（GitHub 存放文件的位置；github.com 会自动转到这里）",
                [Key.ConsentWhy] = "目的",
                [Key.ConsentWhyText] = "获取 {0}，仅一次。",
                [Key.ConsentSent] = "发送内容",
                [Key.ConsentSentText] = "只有普通的 HTTPS 请求和 User-Agent {0}。不发送你的名字、文件夹位置、登录信息或 Cookie。与任何网站一样，GitHub 能看到你的 IP 地址。",
                [Key.ConsentCheck] = "校验",
                [Key.ConsentCheckText] = "只有 SHA-256 与此模组发布中记录的值一致时才会使用。在此之前游戏文件夹不会有任何更改。",
                [Key.ConsentCheckTextBoth] = "每个文件只有 SHA-256 与此模组发布（ModFramework）或安装器（BepInEx）中记录的值一致时才会使用。在此之前游戏文件夹不会有任何更改。",
                [Key.ConsentNoApi] = "不会连接 api.github.com。选择你自己下载的 zip 则完全不使用互联网。",
                [Key.ConsentNoApiBepInEx] = "不会连接 api.github.com。即使选择自己下载的 ModFramework zip，仍会下载 BepInEx。",
                [Key.OpenReleasePage] = "打开发布页",
                [Key.ChooseZip] = "选择 zip(&Z)...",
                [Key.DownloadAndInstall] = "下载并安装(&D)",
                [Key.CancelPlain] = "取消",
                [Key.ChooseZipTitle] = "选择 {0}",
                [Key.NetOffline] = "安装器无法连接到互联网。",
                [Key.NetBusy] = "GitHub 没有响应或返回了错误。请几分钟后重试。",
                [Key.NetLimited] = "GitHub 目前正在限制下载。请在 {0} 分钟后重试。",
                [Key.NetLimitedLater] = "GitHub 目前正在限制下载。请稍后重试。",
                [Key.NetTls] = "无法确认与 GitHub 的安全连接。",
                [Key.FwNotPublished] = "ModFramework {0} 尚未发布。请告知模组作者。",
                [Key.FwDownloadFailed] = "无法下载 ModFramework {0}。",
                [Key.FwSize] = "下载的 ModFramework {0} 的大小与此模组发布中记录的不同。",
                [Key.FwHash] = "下载的 ModFramework {0} 与此模组发布中记录的不一致（SHA-256）。",
                [Key.FwLocalMismatch] = "所选的 zip 不是此模组发布中记录的 ModFramework {0}（大小或 SHA-256 不同）。",
                [Key.FwNoDownload] = "需要下载 ModFramework {0}，但下载已关闭（--no-download）。请用 --framework-zip 指定 zip。",
                [Key.BepInExNoDownload] = "需要下载 BepInEx {0}，但下载已关闭（--no-download）。请用 --bepinex-zip 指定 zip。",
                [Key.FwZipLacks] = "ModFramework {0} 中没有此模组需要的 {1}。请告知模组作者。",
                [Key.FwZipTooOld] = "ModFramework {0} 中的 {1} 是 {2}，但此模组需要 {3} 或更高版本。请告知模组作者。",
                [Key.FwKeepNotMet] = "已安装的 ModFramework 不满足此模组的最低要求，因此需要安装 ModFramework {0}。",
                [Key.NothingChanged] = "游戏文件夹没有任何更改。",
                [Key.FwDeletedHelp] = "该文件未被使用并已删除。游戏文件夹没有任何更改。",
                [Key.FwNotUsedHelp] = "该 zip 未被使用。游戏文件夹没有任何更改。",
                [Key.FwManualHelp] = "你也可以从发布页自行下载 zip，并用“选择 zip”选中它。它会以同样的方式校验。",
                [Key.FwReleaseLink] = "打开发布页（{0}）",
                [Key.FwKeepLink] = "保留 ModFramework {0}，只安装模组（它满足此模组的最低要求）",
            },
        };

        internal static readonly string[] Languages = { "en", "ja", "zh" };

        internal static string Current = Detect();

        internal static string Detect()
        {
            string name = CultureInfo.CurrentUICulture.Name;
            if (name.StartsWith("ja")) return "ja";
            if (name.StartsWith("zh")) return "zh";
            return "en";
        }

        internal static string Get(Key key, params object[] args)
        {
            string text = All.TryGetValue(Current, out var table) && table.TryGetValue(key, out string s) ? s : All["en"][key];
            return args.Length == 0 ? text : string.Format(text, args);
        }

        // For bug reports and the log, which stay English whatever the window shows.
        internal static string English(Key key, params object[] args)
        {
            return args.Length == 0 ? All["en"][key] : string.Format(All["en"][key], args);
        }

        // The windows' font for the installer language. Windows' own font for another
        // script draws the missing characters from a fallback font it did not measure
        // them with, so a line that should wrap ran past the right edge instead (Chinese
        // on Japanese Windows). Windows in the language itself keeps its own font.
        internal static Font UiFont()
        {
            Font system = SystemFonts.MessageBoxFont;
            string ui = CultureInfo.CurrentUICulture.Name;
            string family =
                Current == "ja" && !ui.StartsWith("ja") ? "Yu Gothic UI" :
                Current == "zh" && !(ui == "zh-CN" || ui == "zh-SG" || ui.StartsWith("zh-Hans")) ? "Microsoft YaHei UI" :
                null;
            if (family == null)
            {
                return system;
            }
            var font = new Font(family, system.SizeInPoints);
            if (font.Name == family)
            {
                return font;
            }
            // Not installed (Windows 7 has no Yu Gothic UI): Windows' own font as before.
            font.Dispose();
            return system;
        }

        internal static string LanguageName(string code)
        {
            switch (code)
            {
                case "ja": return "日本語";
                case "zh": return "中文";
                default: return "English";
            }
        }
    }
}
